#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
程序实现读取contact.txt文本文件，提示用户输入搜索字符串，逐行处理进行字符串比较，高亮显示匹配的内容和搜索到包含
搜索内容的行数
'''
__author__ = 'niming'


found_records = 0 #包含搜索内容的行数

f = file("contact.txt",'r')

while True:

    search_keyword = raw_input("Search info:")

    for line in f.xreadlines(): #逐行读取文件行
        match_count = line.count(search_keyword) #检查该行字符串包含搜索字符串的次数
        if match_count:
            for i in range(match_count):
                #通过字符串替换方法实现高亮显示搜索字符串
                print_line =  line.replace(search_keyword, "\033[32;1m%s\033[0m" % search_keyword)
            print print_line
            found_records += 1

    continue_flag = raw_input("Found %d records.Continue?(yes/no):" % found_records)

    if continue_flag == "yes":
        f.seek(0)
        found_records = 0
        search_keyword = ""
    else:
        break

f.close()
